project_id = "qfgvgpyzydtkpuotkvbn"

[functions.postgres-ops]
verify_jwt = false

[functions.parse-file]
verify_jwt = false

[functions.run-import]
verify_jwt = false

[functions.external-data]
verify_jwt = false
