project_id = "qfgvgpyzydtkpuotkvbn"

[functions.ftp-test]
verify_jwt = false

[functions.ftp-fetch]
verify_jwt = false

[functions.pgp-decrypt]
verify_jwt = false

[functions.parse-file]
verify_jwt = false

[functions.run-import]
verify_jwt = false
